name: 'Publish Docs'
description: 'Publish documentation to GitHub pages'
inputs:
  folder:
    description: Folder to deploy to GH pages
    required: true
    type: string
  version:
    description: Deployment target
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: 'gh-pages'
        path: 'gh-pages'
    - run: rm -rf gh-pages/${{ inputs.version }}  # to ensure a clean build
      shell: bash
    - run: cp -r ${{ inputs.folder }} gh-pages/${{ inputs.version }}
      shell: bash

    - run: git config user.name "github-docs-action[bot]"
      shell: bash
      working-directory: gh-pages
    - run: git config user.email "github-docs-action[bot]@users.noreply.github.com"
      working-directory: gh-pages
      shell: bash
    - run: git add -A && git commit -m"Update gh-pages"
      shell: bash
      working-directory: gh-pages
    - run: git push origin gh-pages
      shell: bash
      working-directory: gh-pages
