name: 'Publish Docs'
description: 'Publish documentation to GitHub pages'
inputs:
  branch:
    default: gh-pages
    description: Branch to deploy to
    required: false
    type: string
  folder:
    description: Folder to deploy to GH pages
    required: true
    type: string
  token:
    description: GitHub OAuth token
    required: true
    type: string
  url:
    description: Base URL of the GitHub pages
    required: true
    type: string
  version:
    description: Deployment target
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Clone repository for pages
      run: |
        git clone https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git gh-pages \
          --depth 1 --single-branch --branch ${{ inputs.branch }} \
          --config user.email="github-docs-action[bot]@users.noreply.github.com" \
          --config user.name="github-docs-action[bot]"
      shell: bash
    - name: Copy changes
      run: |
        git reset $(git log --format="%H" | tail -1)
        rm -rf ${{ inputs.version }}
        cp -r ${{ inputs.folder }} ${{ inputs.version }}
      shell: bash
      working-directory: gh-pages
    - name: Generate files
      run: python ${{ github.action_path }}/generate-files.py --base=gh-pages --url=${{ inputs.url }}
      shell: bash

    - name: Commit changes
      run: git add -A && git commit -m"Update gh-pages ref=${{ github.ref }}"
      shell: bash
      working-directory: gh-pages
    - name: Push
      run: git push --force https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git gh-pages \
      shell: bash
      working-directory: gh-pages
