name: Docs

on:
  workflow_dispatch:
    inputs:
      publish:
        default: false
        description: Publish docs
        required: false
        type: boolean
      version:
        description: Deploy to version
        required: true
        type: string
  workflow_call:
    inputs:
      publish:
        default: false
        required: false
        type: boolean
      version:
        required: true
        type: string

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt install --yes pandoc
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/docs.txt
      - run: python -m sphinx -j2 -v -b html -d docs_doctrees docs html/${{ inputs.version }}
      - uses: actions/upload-artifact@v3
        with:
          name: documentation-${{ inputs.version }}
          path: html/${{ inputs.version }}
      - uses: ./.github/actions/publish-docs
        name: Publish documentation
        if: ${{ inputs.publish }}
        with:
          folder: ${GITHUB_WORKSPACE}/html/${{ inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          url: https://jl-wynen.github.io/sphinx-version-test
          version: ${{ inputs.version }}
