name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    needs: upload_packages
    uses: ./.github/workflows/docs.yml
    with:
      publish: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    secrets: inherit
